### ISSUE TITLE
PyPI package

### ISSUE THREAD

**Issue by SeanPedersen** [lagelalegal/pylint-sqlalchemy#2]
Would be nice if this would be available via pip!

There is another package with the same name but it does not work: https://github.com/gwax/pylint-sqlalchemy/issues/1

An alternative installable via pip or conda would be great!

**Comment by lagelalegal** [comment]
Ok, I'm so sorry, I'm try do it.

**Comment by lagelalegal** [comment]
Hey man, This project  been merged.
You can use it to install.
```
pip install pylint-sqlalchemy
```
Finally, thank you very much for your advice.
